// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Xo3djrCOSWhioYuJjHJ6tkTtQzSfwJw',
    appId: '1:161209537537:web:a60229a70d42e985e6dc00',
    messagingSenderId: '161209537537',
    projectId: 'apptuan89-88fcf',
    authDomain: 'apptuan89-88fcf.firebaseapp.com',
    storageBucket: 'apptuan89-88fcf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx6QbxCLAGotyB83pPSRND8NI5izMF2sw',
    appId: '1:161209537537:android:f4911be7ee67df7de6dc00',
    messagingSenderId: '161209537537',
    projectId: 'apptuan89-88fcf',
    storageBucket: 'apptuan89-88fcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_WcOU28IZCRktFkHsFw25xgtTMgJr6o',
    appId: '1:161209537537:ios:8235edc5f3cba717e6dc00',
    messagingSenderId: '161209537537',
    projectId: 'apptuan89-88fcf',
    storageBucket: 'apptuan89-88fcf.firebasestorage.app',
    iosBundleId: 'com.example.appTuan89',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_WcOU28IZCRktFkHsFw25xgtTMgJr6o',
    appId: '1:161209537537:ios:8235edc5f3cba717e6dc00',
    messagingSenderId: '161209537537',
    projectId: 'apptuan89-88fcf',
    storageBucket: 'apptuan89-88fcf.firebasestorage.app',
    iosBundleId: 'com.example.appTuan89',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Xo3djrCOSWhioYuJjHJ6tkTtQzSfwJw',
    appId: '1:161209537537:web:66252c828136ae77e6dc00',
    messagingSenderId: '161209537537',
    projectId: 'apptuan89-88fcf',
    authDomain: 'apptuan89-88fcf.firebaseapp.com',
    storageBucket: 'apptuan89-88fcf.firebasestorage.app',
  );
}


